#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 04 12:27:09 +07 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto edaff91fac3f4d3cadf6af842e30a02d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot testSinglePulser_behav xil_defaultlib.testSinglePulser xil_defaultlib.glbl -log elaborate.log"
xelab -wto edaff91fac3f4d3cadf6af842e30a02d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot testSinglePulser_behav xil_defaultlib.testSinglePulser xil_defaultlib.glbl -log elaborate.log

