webtalk_init -webtalk_dir /home/chutchatut/work/HW Syn Lab/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/testDFlipFlop_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 12 18:15:48 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7c3b64ac-d204-41ed-861c-33bd7ba5d756" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1f2d95e6c1c44199901bb82124661e36" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2397.584 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "115236_KB" -context "xsim\\usage"
webtalk_transmit -clientid 230538501 -regid "" -xml /home/chutchatut/work/HW Syn Lab/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/testDFlipFlop_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/chutchatut/work/HW Syn Lab/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/testDFlipFlop_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/chutchatut/work/HW Syn Lab/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/testDFlipFlop_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
